/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllBooks: typeof import('./src/components/AllBooks.vue')['default']
    APITest: typeof import('./src/components/APITest.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    BookInfo: typeof import('./src/components/BookInfo.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DataView: typeof import('primevue/dataview')['default']
    DynamicDialog: typeof import('primevue/dynamicdialog')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Manga: typeof import('./src/components/Manga.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Novels: typeof import('./src/components/Novels.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTop: typeof import('primevue/scrolltop')['default']
    Slider: typeof import('primevue/slider')['default']
    Stats: typeof import('./src/components/Stats.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Wishlist: typeof import('./src/components/Wishlist.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
